spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: after_route
              uri: http://192.168.1.24:8083
              predicates:
                - Path=/oauth2/**

logbook:
  format:
    style: http

logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.cloud.gateway.handler: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.cloud.gateway.handler.FilteringWebHandler: TRACE
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
