spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: callback
              uri: http://${LOCAL_IP}:8083
              predicates:
                - Path=/oauth2/callback, /oauth2/login, /oauth2/redirect
            - id: authorize
              uri: http://${LOCAL_IP}:8082
              predicates:
                - Path=/oauth2/authorize, /oauth2/token, /login, /default-ui.css
logbook:
  format:
    style: http

logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.cloud.gateway.handler: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.cloud.gateway.handler.FilteringWebHandler: TRACE
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
