[versions]
spring-boot = "3.5.6"
spring-cloud = "2025.0.0"
authorization = "1.3.1"
junit = "5.10.0"
kotlin = "2.2.20"
global = "1.0.0-SNAPSHOT"
image = "alejandroa714/zulu-alpine-java:21.0.8-jdk-headless"
mysql = "9.4.0"
logbook = "3.12.3"
spotless = "6.25.0"
lombok = "1.18.42"
caffeine = "3.2.3"

[libraries]
bom = { group = "com.sv.youapp.infrastructure", name = "bom" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }
spring-cloud-dependencies = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version.ref = "spring-cloud" }
logbook-bom = { group = "org.zalando", name = "logbook-bom", version.ref = "logbook" }

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
netty = { group = "io.projectreactor.netty", name = "reactor-netty-http" }
caffeine-cache = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
mysql-connector = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }

spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-redis = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis" }
spring-boot-starter-logbook = { group = "org.zalando", name = "logbook-spring-boot-webflux-autoconfigure" }
spring-boot-servlet-logbook = { group = "org.zalando", name = "logbook-spring-boot-starter"}
spring-cloud-starter-gateway = { group = "org.springframework.cloud", name = "spring-cloud-starter-gateway-server-webflux" }
spring-boot-starter-tomcat = { group = "org.springframework.boot", name = "spring-boot-starter-tomcat" }
spring-boot-starter-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-starter-undertow = { group = "org.springframework.boot", name = "spring-boot-starter-undertow" }
spring-boot-starter-oauth2 = { group = "org.springframework.boot", name = "spring-boot-starter-oauth2-authorization-server" }

spring-core-oauth2 = { group = "org.springframework.security", name = "spring-security-oauth2-core" }
spring-authorization-server = { group = "org.springframework.security", name = "spring-security-oauth2-authorization-server", version.ref = "authorization" }


[bundles]
gateway = [
    "spring-cloud-starter-gateway",
    "netty",
    "spring-boot-starter-logbook"

]
web-flux = [
    "spring-boot-starter-webflux",
    "spring-boot-starter-actuator",
    "spring-boot-starter-logbook"
]
web = [
    "spring-boot-starter-web",
    "spring-boot-starter-actuator",
    "spring-boot-starter-undertow",
    "spring-boot-servlet-logbook"
]

[plugins]
java-api = { id = "java"}
publish = { id = "maven-publish"}
java-library = { id = "java-library"}
java-platform = { id = "java-platform"}
java-gradle = { id = "java-gradle-plugin"}
formatter = { id = "com.sv.youapp.infrastructure.formatter"}
tools-jib = { id = "com.google.cloud.tools.jib", version = "3.4.5"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot"}
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin"}
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring" , version.ref = "kotlin"}

