server:
  port: 8083
security:
  oauth2:
    #url: http://${LOCAL_IP}:8082
    url: https://wombed-intramuscular-lanell.ngrok-free.app
    client-id: ${CLIENT_USERNAME}
    client-secret: ${CLIENT_SECRET_PLAIN}

spring:
  main:
    web-application-type: reactive

logbook:
  format:
    style: http

logging:
  level:
    #org.springframework.boot.autoconfigure: DEBUG
    org.zalando.logbook: TRACE
